---
title: "git_01"
author: "Juan Guardado"
date: "Spring Semester"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I have been one acquainted with the night.  
I have walked out in rain—and back in rain.  
I have outwalked the furthest city light.  
I have looked down the saddest city lane.  
I have passed by the watchman on his beat  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —    
And this was odd, because it was  
The middle of the night.  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Here,  
    With my beer  
I sit,  
While golden moments flit:  
    Alas!  
    They pass  
Unheeded by:  
And, as they fly,  
I,  
Being dry,  
    Sit, idly sipping here  
    My beer.  

O, finer far  
Than fame, or...  
